### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by dulunar** [alexpreynolds/kmer-counter#6] opened 2020-03-30 13:33 UTC
make
g++ -g -Wall -Wextra -std=c++14 -D__STDC_CONSTANT_MACROS -D__STDINT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -O3 -static -c kmer-counter.cpp -o kmer-counter.o
In file included from kmer-counter.cpp:1:0:
kmer-counter.hpp: In static member function ‘static int kmer_counter::KmerCounter::mkpath(const char*, mode_t)’:
kmer-counter.hpp:203:23: error: ‘runtime_error’ is not a member of ‘std’
                 throw std::runtime_error(msg_buf);
                       ^
In file included from kmer-counter.hpp:30:0,
                 from kmer-counter.cpp:1:
hash_map.hpp: In instantiation of ‘emilib::HashMap<KeyT, ValueT, HashT, CompT>& emilib::HashMap<KeyT, ValueT, HashT, CompT>::operator=(const emilib::HashMap<KeyT, ValueT, HashT, CompT>&) [with KeyT = std::basic_string<char>; ValueT = int; HashT = std::hash<std::basic_string<char> >; CompT = emilib::HashMapEqualTo<std::basic_string<char> >]’:
kmer-counter.hpp:216:93:   required from here
hash_map.hpp:196:32: error: ‘cbegin’ was not declared in this scope
             insert(cbegin(other), cend(other));
                                ^
hash_map.hpp:196:45: error: ‘cend’ was not declared in this scope
             insert(cbegin(other), cend(other));
                                             ^
hash_map.hpp: In instantiation of ‘emilib::HashMap<KeyT, ValueT, HashT, CompT>::HashMap(const emilib::HashMap<KeyT, ValueT, HashT, CompT>&) [with KeyT = std::basic_string<char>; ValueT = int; HashT = std::hash<std::basic_string<char> >; CompT = emilib::HashMapEqualTo<std::basic_string<char> >]’:
kmer-counter.cpp:64:31:   required from here
hash_map.hpp:184:32: error: ‘cbegin’ was not declared in this scope
             insert(cbegin(other), cend(other));
                                ^
hash_map.hpp:184:45: error: ‘cend’ was not declared in this scope
             insert(cbegin(other), cend(other));
                                             ^
make: *** [kmer-counter] Error 1

**Comment by alexpreynolds** [comment] 2020-03-30 18:17
I was not able to reproduce this error under Mac OS X 10.15.3 (Apple clang version 11.0.3 (clang-1103.0.32.29)) or Ubuntu 18.04.4 (GNU gcc 7.5.0, glibc 2.27).

However, the error messages suggest some adjustment to import statements, which I have applied in commit 9471498. 

Please feel free to try this patch and let me know if it helps. If not, if you can please let me know what kind of environment you're running this under, that would help with troubleshooting.

**Comment by alexpreynolds** [comment] 2020-03-31 20:14
I'm seeing these errors in Cygwin 2.0.4 (gcc 4.9.3).

**Comment by alexpreynolds** [comment] 2020-03-31 22:41
I am not seeing these errors in Cygwin 3.1.4 (gcc 9.3.0). 

Because the error messages with the older version of Cygwin were identical, I'm assuming that you're using Cygwin and so I'd recommend upgrading it and the development kit to the latest versions available to you.

* https://cygwin.com/install.html
* https://preshing.com/20141108/how-to-install-the-latest-gcc-on-windows

I'm going to close this up. Feel free to follow up if your environment is different.

**Closed as completed by alexpreynolds** 2020-03-31 22:41 UTC
Labels: question
